cluster.name: kubernetes-logging

node.name: ${HOSTNAME}
node.master: true
node.data: true

transport.profiles.default.port: 9300
http.port: 9200

path.data: /data

indices.fielddata.cache.size:  40%
